# Replace the connectionString with a valid value before using this component
# https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus/
# https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/#step-1-setup-the-pubsub-component

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: contacts-api-pubsub # Path becomes http://localhost:3500/publish/contacts-api-pubsub
  namespace: default
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString # Required when not using Azure Authentication.
    value: "Azure Service Bus Connection String Goes Here"
  - name: timeoutInSec # Optional
    value: 60
  - name: handlerTimeoutInSec # Optional
    value: 60
  - name: disableEntityManagement # Optional
    value: "false"
  - name: maxDeliveryCount # Optional
    value: 3
  - name: lockDurationInSec # Optional
    value: 60
  - name: lockRenewalInSec # Optional
    value: 20
  - name: maxActiveMessages # Optional
    value: 2000
  - name: maxActiveMessagesRecoveryInSec # Optional
    value: 2
  - name: maxConcurrentHandlers # Optional
    value: 10
  - name: prefetchCount # Optional
    value: 5
  - name: defaultMessageTimeToLiveInSec # Optional
    value: 10
  - name: autoDeleteOnIdleInSec # Optional
    value: 3600
  - name: maxReconnectionAttempts # Optional
    value: 30
  - name: connectionRecoveryInSec # Optional
    value: 2
  - name: publishMaxRetries # Optional
    value: 5
  - name: publishInitialRetryInternalInMs # Optional
    value: 500
scopes:
  - contacts-api
