apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: contacts-api-pubsub # Path becomes http://localhost:3500/publish/contacts-api-pubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
scopes:
- contacts-api