apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub # This is the default dapr pubsub, but for this project we are using pubsub-rabbitmq.yaml instead
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""